version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: archdb
      POSTGRES_DB: archdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: archdb
      POSTGRES_DB: archdb
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:archdb@db/archdb
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  postgres_data: